/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AgeRestrictedRouteImport } from './routes/age-restricted'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SerialsSerialSlugRouteImport } from './routes/serials/$serialSlug'
import { Route as CreatorUploadsRouteImport } from './routes/creator/uploads'
import { Route as CreatorUploadRouteImport } from './routes/creator/upload'
import { Route as CreatorSeriesRouteImport } from './routes/creator/series'
import { Route as ClipClipIdRouteImport } from './routes/clip.$clipId'
import { Route as CreatorSeriesNewRouteImport } from './routes/creator/series_.new'
import { Route as CreatorSeriesSeriesIdRouteImport } from './routes/creator/series_.$seriesId'
import { Route as CreatorSeriesSeriesIdEditRouteImport } from './routes/creator/series_.$seriesId.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRestrictedRoute = AgeRestrictedRouteImport.update({
  id: '/age-restricted',
  path: '/age-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerialsSerialSlugRoute = SerialsSerialSlugRouteImport.update({
  id: '/serials/$serialSlug',
  path: '/serials/$serialSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUploadsRoute = CreatorUploadsRouteImport.update({
  id: '/creator/uploads',
  path: '/creator/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUploadRoute = CreatorUploadRouteImport.update({
  id: '/creator/upload',
  path: '/creator/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSeriesRoute = CreatorSeriesRouteImport.update({
  id: '/creator/series',
  path: '/creator/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipClipIdRoute = ClipClipIdRouteImport.update({
  id: '/clip/$clipId',
  path: '/clip/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSeriesNewRoute = CreatorSeriesNewRouteImport.update({
  id: '/creator/series_/new',
  path: '/creator/series/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSeriesSeriesIdRoute = CreatorSeriesSeriesIdRouteImport.update({
  id: '/creator/series_/$seriesId',
  path: '/creator/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSeriesSeriesIdEditRoute =
  CreatorSeriesSeriesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CreatorSeriesSeriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/auth-error': typeof AuthErrorRoute
  '/browse': typeof BrowseRoute
  '/feed': typeof FeedRoute
  '/profile': typeof ProfileRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/creator/series': typeof CreatorSeriesRoute
  '/creator/upload': typeof CreatorUploadRoute
  '/creator/uploads': typeof CreatorUploadsRoute
  '/serials/$serialSlug': typeof SerialsSerialSlugRoute
  '/creator/series/$seriesId': typeof CreatorSeriesSeriesIdRouteWithChildren
  '/creator/series/new': typeof CreatorSeriesNewRoute
  '/creator/series/$seriesId/edit': typeof CreatorSeriesSeriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/auth-error': typeof AuthErrorRoute
  '/browse': typeof BrowseRoute
  '/feed': typeof FeedRoute
  '/profile': typeof ProfileRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/creator/series': typeof CreatorSeriesRoute
  '/creator/upload': typeof CreatorUploadRoute
  '/creator/uploads': typeof CreatorUploadsRoute
  '/serials/$serialSlug': typeof SerialsSerialSlugRoute
  '/creator/series/$seriesId': typeof CreatorSeriesSeriesIdRouteWithChildren
  '/creator/series/new': typeof CreatorSeriesNewRoute
  '/creator/series/$seriesId/edit': typeof CreatorSeriesSeriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/auth-error': typeof AuthErrorRoute
  '/browse': typeof BrowseRoute
  '/feed': typeof FeedRoute
  '/profile': typeof ProfileRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/creator/series': typeof CreatorSeriesRoute
  '/creator/upload': typeof CreatorUploadRoute
  '/creator/uploads': typeof CreatorUploadsRoute
  '/serials/$serialSlug': typeof SerialsSerialSlugRoute
  '/creator/series_/$seriesId': typeof CreatorSeriesSeriesIdRouteWithChildren
  '/creator/series_/new': typeof CreatorSeriesNewRoute
  '/creator/series_/$seriesId/edit': typeof CreatorSeriesSeriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/age-restricted'
    | '/auth-error'
    | '/browse'
    | '/feed'
    | '/profile'
    | '/clip/$clipId'
    | '/creator/series'
    | '/creator/upload'
    | '/creator/uploads'
    | '/serials/$serialSlug'
    | '/creator/series/$seriesId'
    | '/creator/series/new'
    | '/creator/series/$seriesId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/age-restricted'
    | '/auth-error'
    | '/browse'
    | '/feed'
    | '/profile'
    | '/clip/$clipId'
    | '/creator/series'
    | '/creator/upload'
    | '/creator/uploads'
    | '/serials/$serialSlug'
    | '/creator/series/$seriesId'
    | '/creator/series/new'
    | '/creator/series/$seriesId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/age-restricted'
    | '/auth-error'
    | '/browse'
    | '/feed'
    | '/profile'
    | '/clip/$clipId'
    | '/creator/series'
    | '/creator/upload'
    | '/creator/uploads'
    | '/serials/$serialSlug'
    | '/creator/series_/$seriesId'
    | '/creator/series_/new'
    | '/creator/series_/$seriesId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AgeRestrictedRoute: typeof AgeRestrictedRoute
  AuthErrorRoute: typeof AuthErrorRoute
  BrowseRoute: typeof BrowseRoute
  FeedRoute: typeof FeedRoute
  ProfileRoute: typeof ProfileRoute
  ClipClipIdRoute: typeof ClipClipIdRoute
  CreatorSeriesRoute: typeof CreatorSeriesRoute
  CreatorUploadRoute: typeof CreatorUploadRoute
  CreatorUploadsRoute: typeof CreatorUploadsRoute
  SerialsSerialSlugRoute: typeof SerialsSerialSlugRoute
  CreatorSeriesSeriesIdRoute: typeof CreatorSeriesSeriesIdRouteWithChildren
  CreatorSeriesNewRoute: typeof CreatorSeriesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-restricted': {
      id: '/age-restricted'
      path: '/age-restricted'
      fullPath: '/age-restricted'
      preLoaderRoute: typeof AgeRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serials/$serialSlug': {
      id: '/serials/$serialSlug'
      path: '/serials/$serialSlug'
      fullPath: '/serials/$serialSlug'
      preLoaderRoute: typeof SerialsSerialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/uploads': {
      id: '/creator/uploads'
      path: '/creator/uploads'
      fullPath: '/creator/uploads'
      preLoaderRoute: typeof CreatorUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/upload': {
      id: '/creator/upload'
      path: '/creator/upload'
      fullPath: '/creator/upload'
      preLoaderRoute: typeof CreatorUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/series': {
      id: '/creator/series'
      path: '/creator/series'
      fullPath: '/creator/series'
      preLoaderRoute: typeof CreatorSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$clipId': {
      id: '/clip/$clipId'
      path: '/clip/$clipId'
      fullPath: '/clip/$clipId'
      preLoaderRoute: typeof ClipClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/series_/new': {
      id: '/creator/series_/new'
      path: '/creator/series/new'
      fullPath: '/creator/series/new'
      preLoaderRoute: typeof CreatorSeriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/series_/$seriesId': {
      id: '/creator/series_/$seriesId'
      path: '/creator/series/$seriesId'
      fullPath: '/creator/series/$seriesId'
      preLoaderRoute: typeof CreatorSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/series_/$seriesId/edit': {
      id: '/creator/series_/$seriesId/edit'
      path: '/edit'
      fullPath: '/creator/series/$seriesId/edit'
      preLoaderRoute: typeof CreatorSeriesSeriesIdEditRouteImport
      parentRoute: typeof CreatorSeriesSeriesIdRoute
    }
  }
}

interface CreatorSeriesSeriesIdRouteChildren {
  CreatorSeriesSeriesIdEditRoute: typeof CreatorSeriesSeriesIdEditRoute
}

const CreatorSeriesSeriesIdRouteChildren: CreatorSeriesSeriesIdRouteChildren = {
  CreatorSeriesSeriesIdEditRoute: CreatorSeriesSeriesIdEditRoute,
}

const CreatorSeriesSeriesIdRouteWithChildren =
  CreatorSeriesSeriesIdRoute._addFileChildren(
    CreatorSeriesSeriesIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AgeRestrictedRoute: AgeRestrictedRoute,
  AuthErrorRoute: AuthErrorRoute,
  BrowseRoute: BrowseRoute,
  FeedRoute: FeedRoute,
  ProfileRoute: ProfileRoute,
  ClipClipIdRoute: ClipClipIdRoute,
  CreatorSeriesRoute: CreatorSeriesRoute,
  CreatorUploadRoute: CreatorUploadRoute,
  CreatorUploadsRoute: CreatorUploadsRoute,
  SerialsSerialSlugRoute: SerialsSerialSlugRoute,
  CreatorSeriesSeriesIdRoute: CreatorSeriesSeriesIdRouteWithChildren,
  CreatorSeriesNewRoute: CreatorSeriesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
