/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SerialsSerialIdRouteImport } from './routes/serials/$serialId'

const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerialsSerialIdRoute = SerialsSerialIdRouteImport.update({
  id: '/serials/$serialId',
  path: '/serials/$serialId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-error': typeof AuthErrorRoute
  '/serials/$serialId': typeof SerialsSerialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-error': typeof AuthErrorRoute
  '/serials/$serialId': typeof SerialsSerialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-error': typeof AuthErrorRoute
  '/serials/$serialId': typeof SerialsSerialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/auth-error' | '/serials/$serialId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/auth-error' | '/serials/$serialId'
  id: '__root__' | '/' | '/account' | '/auth-error' | '/serials/$serialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthErrorRoute: typeof AuthErrorRoute
  SerialsSerialIdRoute: typeof SerialsSerialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serials/$serialId': {
      id: '/serials/$serialId'
      path: '/serials/$serialId'
      fullPath: '/serials/$serialId'
      preLoaderRoute: typeof SerialsSerialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthErrorRoute: AuthErrorRoute,
  SerialsSerialIdRoute: SerialsSerialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
